'use client';

import { useCallback, useState } from 'react';
import { useToast } from '@/components/ui/toast';
import { ReportsTab } from '@/components/tabs';
import { Modal } from '@/components/ui/modal';
import { Button } from '@/components/ui/button';
import { CalendarClock, BarChart3 } from 'lucide-react';

export default function ReportsPage() {
  const { showToast } = useToast();
  const [modalState, setModalState] = useState<{
    isOpen: boolean;
    title: string;
    content: React.ReactNode;
  }>({ isOpen: false, title: '', content: null });

  const closeModal = () => setModalState({ isOpen: false, title: '', content: null });

  const handleSaveSharing = useCallback(() => {
    showToast('Sharing settings saved!');
  }, [showToast]);

  const handleConfigureReporting = useCallback(() => {
    showToast('Reporting configuration saved!');
  }, [showToast]);

  const handleViewReport = useCallback((title: string) => {
    setModalState({
      isOpen: true,
      title: title,
      content: (
        <div className="space-y-6">
          <div className="flex items-center gap-3 text-muted-foreground text-sm pb-4 border-b">
            <div className="flex items-center gap-1">
              <CalendarClock className="w-4 h-4" />
              <span>Dec 4, 2025</span>
            </div>
            <div className="w-1 h-1 rounded-full bg-border" />
            <div>Generated by AI Agent</div>
          </div>
          
          <div className="bg-secondary/20 p-6 rounded-lg border border-dashed text-center py-12">
             <BarChart3 className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-sm text-muted-foreground max-w-md mx-auto">
              Report content for &quot;<span className="font-semibold text-foreground">{title}</span>&quot; would be displayed here with full details,
              charts, and analysis.
            </p>
          </div>
          
          <div className="flex justify-end">
            <Button onClick={closeModal}>Close Preview</Button>
          </div>
        </div>
      ),
    });
  }, []);

  const handleShareReport = useCallback(
    (title: string) => {
      showToast(`Sharing "${title}"...`);
    },
    [showToast]
  );

  const handleExportReport = useCallback(
    (title: string) => {
      showToast(`Exporting "${title}"...`);
    },
    [showToast]
  );

  return (
    <>
      <ReportsTab
        onSaveSharing={handleSaveSharing}
        onConfigureReporting={handleConfigureReporting}
        onViewReport={handleViewReport}
        onShareReport={handleShareReport}
        onExportReport={handleExportReport}
      />
      <Modal
        isOpen={modalState.isOpen}
        onClose={closeModal}
        title={modalState.title}
      >
        {modalState.content}
      </Modal>
    </>
  );
}

